### ISSUE TITLE
need ompi_autogen_arguments option

### ISSUE THREAD

**Issue by ggouaillardet** [open-mpi/mtt#419]
If ompi (master for now) is retrieved as a tarball, and ```ompi_autogen``` is 1, then ```autogen.pl``` must be invoked with ```--force```
in order to have a generic mechanism, I will implement the ```ompi_autogen_arguments``` in the ompi MPI install module.
then @jsquyres will have to update Cisco mtt config file for master (and v2.x? now ?) to pass ```--force```

**Comment by jsquyres** [comment]
Should be fixed via #420.
