### ISSUE TITLE
client accepts multiple .ini files but only runs the last .ini file

### ISSUE THREAD

**Issue by noahv** [open-mpi/mtt#436]
Description of problem: 

MTT client accepts multiple .ini files but only runs the last .ini file

Version-Release number of selected component (if applicable): 

MTT commit 84b227219f78125fab10a56d11d59bbe92dced28

Steps to Reproduce:
 /home/test/jenkins/mtt/pyclient/pymtt.py --base-dir=/home/test/jenkins/mtt/pylib <inifile#1>.ini <inifile#2>.ini

Actual results:

 Only the final .ini file is run.

Expected results: 
 
 All .ini files should be run

Additional info:

**Comment by DebRez** [comment]
I am working on a fix for this. 

@rhc54
