### ISSUE TITLE
The MTT --section switch still runs all sections

### ISSUE THREAD

**Issue by noahv** [open-mpi/mtt#437]
Description of problem: 

  The MTT --section switch still runs all sections.

Version-Release number of selected component (if applicable): 

  MTT commit 84b227219f78125fab10a56d11d59bbe92dced28

Steps to Reproduce:

  /home/test/jenkins/mtt/pyclient/pymtt.py --base-dir=/home/test/jenkins/mtt/pylib --section=TestGet <inifile>.ini

Actual results:

All sections are run instead of just TestGet

**Comment by DebRez** [comment]
I will work this fix into the combinatorial executor changes being made.

**Comment by noahv** [comment]
Issue is fixed.  Tested with 

`/opt/mtt/pyclient/pymtt.py --base-dir=/opt/mtt/pylib/ --verbose --clean-start --section Profile:Installed,Reporter:Console /opt/mtt/samples/python/ompi_hello_world.ini`
