### ISSUE TITLE
Cherrypy expects wrong path for virtualenv site-packages

### ISSUE THREAD

**Issue by ribab** [open-mpi/mtt#444]
The cherrypy server installation script located in `mtt/server/php/cherrypy/bin/mtt_server_install.py` expects to find the `site-packages` folder it generated using virtualenv within the `src/env/lib/python/site-packages/` path, however the path that is actually generated by virtualenv is `src/env/lib/python2.7/site-packages/`.

A simple fix is to change the text "python" to "python2.7" in this line in the "mtt_server_install.py" file mentioned above:

    call(['cp', '-rs', cwd + '/' + source_dir + '/' + package_name,
      env_dir + '/lib/python/site-packages/' + package_name])

I am hesitant for this fix since I am unsure whether python virtualenv generates `src/env/lib/python2.7/site-packages/` for everyone, or if some systems use the `src/env/lib/python/site-packages/` path for their version of virtualenv.

**Comment by jjhursey** [comment]
Yeah, we should investigate this some more. I suspect that it's environment specific (so will match the version of python being used). We might be able to make the script smarter to detect the name of the environment and use it in the path construction.

**Comment by jjhursey** [comment]
It looks like virtualenv has a `cdsitepackages` key that might solve this:
  * http://docs.python-guide.org/en/latest/dev/virtualenvs/
