### ISSUE TITLE
result_stderr not packaged properly in Pyclient for submit

### ISSUE THREAD

**Issue by jjhursey** [open-mpi/mtt#468]
See the conversation here:
- https://mail-archive.com/mtt-devel@lists.open-mpi.org/msg00686.html

It looks like the `result_stderr` key is passed as an array containing one string, instead of passing just the string.

Note that `result_stdout` is being packaged properly.

**Comment by ribab** [comment]
The problem is that the "join" command is used in IUDatabase.py, and previous steps already converted stderr to a string.

I will look through the rest of the code and make sure that both stdout and stderr are handled consistently.

**Comment by rhc54** [comment]
Just FYI: the execute_cmd plugin now returns stdout/stderr as lists. This was done in order to support the truncation directive. I adjusted the code in IUDatabase to properly handle stdout/stderr submission, but code that uses execute_cmd will need similar adjustments

**Comment by hppritcha** [comment]
@DebRez if you have time could you take a look at this?
