### ISSUE TITLE
Python client should cd to the scratch directory by default for all plugins

### ISSUE THREAD

**Issue by noahv** [open-mpi/mtt#589]
Currently some plugins will cd into a given target directory such as the TestGet target.  However, other plugins do not cd into the scratch directory and can leave artifacts in the location where the python client executes.  The Junit xml plugin is an example of a plugin that does not cd into scratch or a sub-dir of scratch.

This enhancement request is to modify the default behavior to always cd into the scratch directory and other sub directories as needed.

**Comment by PeterGottesman** [comment]
@ribab did your fix ever get merged? I am running into stray files across the directory I executed in and $HOME that should have ended up in scratch

**Comment by ribab** [comment]
@PeterGottesman I'm looking at the code and I don't see my change in there

https://github.com/open-mpi/mtt/compare/master...ribab:topic/chdir_to_scratch_by_default

I will test my old branch today and see if I can just make a pull request

**Comment by PeterGottesman** [comment]
Thanks!

**Comment by ribab** [comment]
We are moving away from doing ANY cd'ing at all.

We will move towards using absolute paths.

I am closing this :)
