### ISSUE TITLE
New v3 tables cause Perl client to fail

### ISSUE THREAD

**Issue by jjhursey** [open-mpi/mtt#597]
The recent commit (https://github.com/open-mpi/mtt/commit/348b56b7e4e01d0d1189416500c0d31aa84b5c41) introduced new tables to the v3 database schema. We received a report that this causes the Perl client to fail to submit to the database because of the default value set. Email snippet below:

> the perl client cannot always correctly talk to the server with the schema-v3. For example, I have a lot of problems with the bios not being specified during the submission, the server therefore uses the default value (-38) which creates an error.

**Comment by noahv** [comment]
How can I help with this?  Do we need to create a new pull request for https://github.com/gvallee/mtt/tree/gv_dbfix?

**Comment by gvallee** [comment]
I let you guys decide, i could not sign-off the PR, no idea why it is not working. It would be great to have the patch included but there is not much i can personally do at this point.

**Comment by jsquyres** [comment]
What PR are you referring to?  There are no open PRs.

Are you asking for some help with git to get this straightened out?

**Comment by gvallee** [comment]
I close the PR since nothing was happening and I have limited amount of time to spend on this. I do not want to have a PR open for weeks, it is just not productive. It was PR #598

**Comment by noahv** [comment]
We can discuss this today in the MPI Testing Tool Developer Workgroup.   Please let me know if you would like to join us; 11 AM PST.

**Comment by jsquyres** [comment]
Looking at #598, it looks like run-of-the-mill-Git-newbie kinds of issues.  Probably fairly easy to sith down with @gvallee and fix (e.g., on a webex or somesuch).

**Comment by gvallee** [comment]
I already spent time reading the documentation, trying to fix the problem. and it did not help. I don’t have the time to sit in a meeting for a 3-line modification. It is not strait forward, I let someone else get the patch in. Sorry.

**Comment by jsquyres** [comment]
Intel / @ribab it looks like your commit is the one that broke things. Can you please fix things?  It’s been nearly a week since this bug was reported.   Steal from @gvallee’s branch if you need to - he figured out the problem but ran into got issues. If his fix is correct, please make sure to give him credit (i.e., make him the commit author).

**Comment by rhc54** [comment]
It has already been fixed, guys: https://github.com/open-mpi/mtt/commit/57555e71c1273341d452e59cc6c6425f6b8a6815

Committed yesterday afternoon.

**Comment by jsquyres** [comment]
Excellent -- thanks!

**Comment by jjhursey** [comment]
This was fixed by PR #600
