### ISSUE TITLE
OMPI snapshot plugin needs snapshot version mechanism

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/mtt#608]
The Perl client supports a ```ompi_snapshot_version_file ``` mechanism that keeps track of previously tested OMPI tarballs.  This allows the MTT client to avoid unnecessary testing and reporting of duplicate results back to the MTT database.  A similar facility needs to be added to the Python version of the OMPI snapshot plugin.

**Comment by rhc54** [comment]
if you don't get to it, I might be willing to tackle this over the holiday. I also am thinking of converting Jeff's ini file to the Python equivalent during that time.

**Comment by jsquyres** [comment]
That would be great.

@hppritcha and I just had a good conversation about this (i.e., converting Cisco to the python client) while we're physically together for the MPI Forum, too.

**Comment by hppritcha** [comment]
closed via #618
