### ISSUE TITLE
AWS MTT and cherrypy server questions

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/mtt#627]
I'm now using the python client and after various fixes documented by closed issues/PRs, I'm noticing that although the python client appears to successfully submit results to the cherrypy,
that data doesn't seem to show up when using the current viewer.  

Do I need to use special query options with the current viewer to see data submitted to the MTT database at AWS via the cherrypy server?

**Comment by jjhursey** [comment]
You shouldn't. It's all going into the same DB, and the viewer doesn't care where the data is coming from.

If you are submitting them as trial runs (CherryPy was making all submissions trial for a while, but I think we fixed that), then you need to change `Preferences -> Show Trial Runs`. I see one LANL run in the trial set (appears at the bottom of the table).

**Comment by hppritcha** [comment]
hmm... okay by deleting the trial field from the ini file, I now see results from the pyclient in the viewer.  closing this issue and on to the next.
