### ISSUE TITLE
AWS MTT and cherry py server - how to set MPI name for viewer

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/mtt#628]
Now that I'm getting the py client to show results in the current MTT DB viewer, I'm noticing that the "MPI platform" field isn't very useful:
<img width="656" alt="screen shot 2018-02-28 at 11 18 06 pm" src="https://user-images.githubusercontent.com/7818666/36829712-b46a17a4-1cdd-11e8-9274-e50dabcd772b.png">

what field should I be setting in the ini file for the python client to set a sensible value for the MPI platform field in the viewer?

**Comment by hppritcha** [comment]
To be a little clearer, using the python client, I'm getting "Open MPI" as the MPI name, kind of like I might be testing, oh, Intel MPI, Cray MPI, MVAPICH, etc. rather than being focused just on Open MPI releases.

**Comment by hppritcha** [comment]
@jjhursey

**Comment by hppritcha** [comment]
Looks like another area to fix up for Open MPI specific needs.

**Comment by noahv** [comment]
Hi Howard, you are correct.  

The code that detects MPI versions is here https://github.com/open-mpi/mtt/blob/master/pylib/Utilities/MPIVersion.py

We do collect version information and I see it reported in the MTT reporter field MTT Version.

`40 | lanl | NMC-invierno | aarch64 | Linux | Open MPI | 4.0.0a1`

What that information incorrect or missing something that is needed?

**Comment by rhc54** [comment]
@noahv Is it possible that @hppritcha used a plugin that didn't include a call to MPIVersion? I don't recall exactly where that call occurs.

**Comment by noahv** [comment]
Build either shell or autotools

**Comment by rhc54** [comment]
@hppritcha you might just want to check that you went thru a plugin that called MPIVersion to set the field.

**Comment by hppritcha** [comment]
sorry for the delay in response.  i think the issue here is what the Open MPI community is expecting for the MPI name and MPI Version.   For the former, we're wanting something like:

```ompi-nightly-master``` or ```ompi-nightly-v3.0.x``` - i.e. the first part of the tarball name from the nightly download site.
For the MPI version, we're wanting the "repo version" field returned from ```MPI_Get_library_version```, something like ```v3.1.x-201803130241-ea54d44```

I think the code in MPIVersion is a bit too general for what we want for OMPI MTT testing.

**Comment by hppritcha** [comment]
fixed via #641
