### ISSUE TITLE
OMPI_Snapshot Plugin only works with ASIS enabled

### ISSUE THREAD

**Issue by PeterGottesman** [open-mpi/mtt#677]
The ompi_snapshot plugin fails when ASIS is not enabled with the following error:
```
2018-07-24 17:46:53.452164 LOGGING results for MiddlewareGet:OMPIMaster
2018-07-24 17:46:53.452185 =======================================
2018-07-24 17:46:53.452197 Exception was raised: <type 'exceptions.UnboundLocalError'> local variable 'status' referenced before assignment
2018-07-24 17:46:53.452207 =======================================
2018-07-24 17:46:53.452461 Traceback (most recent call last):

  File "/home/pgottesm/PyMTT/mtt/pylib/Tools/Executor/sequential.py", line 283, in execute
    plugin.execute(stageLog, keyvals, testDef)

  File "/home/pgottesm/PyMTT/mtt/pylib/Tools/Fetch/OMPI_Snapshot.py", line 211, in execute
    log['status'] = status

UnboundLocalError: local variable 'status' referenced before assignment
```
From a brief look over the code it looks like the log values are mostly set directly and the variable `status` is only set in one case, when ASIS is enabled. In all other cases, MTT will crash.

**Comment by PeterGottesman** [comment]
@hppritcha Can you take a look at this at some point?

**Comment by hppritcha** [comment]
@PeterGottesman yes we have a new hire who will be working on this.

**Comment by DebRez** [comment]
@PeterGottesman I was only able to recreate your error if I commented out lines 108 to 131 of OMPI_Snapshot.  Otherwise it works to a point with or without asis in the MiddlewareGet section.  Might you have commented out that code on your system?

**Comment by PeterGottesman** [comment]
I did not. I will try to reproduce the error tonight/tomorrow morning and report back what I find.

**Comment by PeterGottesman** [comment]
Here is my brief analysis of the issue and what is causing it. I'm writing this really quick between classes and basing it mostly off of my months old recollection, so let me know if there is something missing or nonsensical.

The error occurs at OMPI_Snapshot.py L212-214:
https://github.com/open-mpi/mtt/blob/cd42d37c232883d3a626c600ac4151868a3327b7/pylib/Tools/Fetch/OMPI_Snapshot.py#L212-L214

For most of the file the pattern followed is to do something like
https://github.com/open-mpi/mtt/blob/cd42d37c232883d3a626c600ac4151868a3327b7/pylib/Tools/Fetch/OMPI_Snapshot.py#L192-L195

In fact, the only place the `status`, `stdout`, and `stderr` variables are set is
https://github.com/open-mpi/mtt/blob/cd42d37c232883d3a626c600ac4151868a3327b7/pylib/Tools/Fetch/OMPI_Snapshot.py#L175-L178
i.e. the code block that is run when `ASIS` is set. So in all other code paths for
this plugin that reach Line 212 the program will fail with an `UnboundLocalError`.

@DebRez The reason you did not see this is because you have already successfully
tested the tarball on your machine so it is being skipped. Try symlinking your
version file to /dev/null to consistently reproduce the bug.

**Comment by DebRez** [comment]
I have tried to replicate the error by deleting the version_file and the entire mttscratch file in between runs. The only time I ever got your error was with the code I mentioned commented out. It cannot be skipping testing the tarball if I have deleted it right?

________________________________

**Comment by PeterGottesman** [comment]
Can you add prints to the codeblock starting at line 174 so it reads 
```python
    # if they want us to leave it as-is, then we are done
            try:
                print("ISSUE 677:", cmds['asis'])
                if cmds['asis']:
                    status = 0
                    stdout = None
                    stderr = None
            except KeyError:
                print("ISSUE 677: KeyError Occurred")
                pass
```

and paste the stdout?

**Comment by PeterGottesman** [comment]
Ah, I see what I was missing. Lines 176-178 aren't the only place `status`, `stdout`, `stderr` are set, it is the only place they are set if the tarball already exists on the system. This means if for some reason the version file doesn't exist (or has the wrong value in it) _and_ mtt has already been run on the current tarball the app will crash if ASIS is not set.
I suspect I ran across this by mistakenly setting the version file to be in a directory which didn't exist or I didn't have write permission to. 
Hope this helps.

**Comment by PeterGottesman** [comment]
Yep, so symlinking to /dev/null is just used for consistently reproducing the issue. You can certainly do a check at the beginning and throw a helpful error message, although as I have outlined the source of the actual crash is that stdout/stderr/status are set inconsistenly.  I think a combination of adding a helpful error message and ensuring the variables are set consistently will both make any issues more clear to the user and avoid any related issues that might pop up in this section of code in the future.
