### ISSUE TITLE
OpenMPI Launcher doesn't use `options` argument

### ISSUE THREAD

**Issue by PeterGottesman** [open-mpi/mtt#679]
The OpenMPI launcher plugin for the python client doesn't seem to use the `options` argument. I am unsure of what the intended usage is, as there is a `command` argument which is what is run.
Is it something that should be removed? Implemented?

**Comment by PeterGottesman** [comment]
@hppritcha Did you have any thoughts on this?

**Comment by hppritcha** [comment]
sorry Peter just saw this.  Its probably a place holder for stuff like additional mpirun arguments.

**Comment by hppritcha** [comment]
actually I'm not sure what this options thingy is for.  I notice starting at line 300 in OpenMPI.py that we're using the cmds dictionary to add options to mpirun.  hmmm... @PeterGottesman

**Comment by rhc54** [comment]
The options list is in every plugin we wrote 😄 It defines the options that are understood by the plugin and sets their default values. We then filter the options given for that stage against it to update them with the user's value here:

https://github.com/open-mpi/mtt/blob/75cd103f305224ac995fad462057c1b34a5de9e6/pylib/Tools/Launcher/OpenMPI.py#L221-L224

So if you want to add an option for the plugin to understand, you add it to the options list along with a default value and explanatory help message. The message gets written out whenever you ask the Python client for help on that plugin.

**Comment by PeterGottesman** [comment]
Sure, but the options dictionary in the OpenMPI plugin has an 'option' key itself, which I was referring to.
https://github.com/open-mpi/mtt/blob/75cd103f305224ac995fad462057c1b34a5de9e6/pylib/Tools/Launcher/OpenMPI.py#L52-L55

This option is defined but it's functionality is never actually implemented.

**Comment by rhc54** [comment]
I see - your question confused me. It certainly _used_ to be implemented so I can only assume it got mistakenly removed. Definitely needs to be implemented.

**Comment by rhc54** [comment]
Sorry about that - hit wrong button 😦

**Comment by rhc54** [comment]
Occurs to me that I owe you a little more explanation. The "options" field is there to allow the stage to define the mpirun cmd line for the identified tests. However, the MTT reporter has certain fields that it expects us to report - e.g., np and any hostfile argument. I suppose we could have parsed the options to look for those, and perhaps that is a more flexible approach. Regardless, we (I should say, I) chose to separately call out the ones we knew we needed to report.

HTH

**Comment by PeterGottesman** [comment]
Per the 8/14/18 telecon, @DebRez will take a look into this.
