### ISSUE TITLE
Python3 - "reload" is not defined

### ISSUE THREAD

**Issue by ribab** [open-mpi/mtt#681]
This is a stackoverflow that describes the problem: https://stackoverflow.com/questions/961162/reloading-module-giving-nameerror-name-reload-is-not-defined

Anywhere where the builtin "reload" is being used in python client is not compatible with python3

**Comment by PeterGottesman** [comment]
Looks like the second answer there is much better than the first, it is in the `imp` module in 3.0-3.3 and `importlib` 3.4+.
Thanks python

**Comment by PeterGottesman** [comment]
Fixed by #689
