### ISSUE TITLE
Utilities/ExecuteCmd.py inconsistent return values

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/mtt#685]
In a code review, we noticed that `ExecuteCmd::execute()` (https://github.com/open-mpi/mtt/blob/master/pylib/Utilities/ExecuteCmd.py#L39) sometimes returns the following for `stdout` and `stderr`:

* `None`
* A string
* A list of strings

It looks like different callers expect different things throughout the code base.  There does not appear to be uniform testing for `None`, for example (which generates errors if you try to execute with `--dry-run`, for example).

Perhaps this function could either:

1. Always return either `None` or a list (even if the list is of length 1 if there's only a single string)
1. Always return a list (even if the list is of length 0, 1, or >1)

I do not fully understand the code base, so I did not want to try to update all the places that call `ExecuteCmd::execute()`.

**Comment by jsquyres** [comment]
Per discussion on the 2018-07-31 MTT call, @ribab said he would have a look at this.

**Comment by rhc54** [comment]
FWIW: it was intended to always return a list of strings as that was the general case

**Comment by PeterGottesman** [comment]
Okay, based on that and the on call discussion, it seems like the second option mentioned is the way to go.

**Comment by ribab** [comment]
I ran into this issue while fixing another bug, so I can reproduce it :)
