### ISSUE TITLE
mttresults.txt file has stderr in single-column mode

### ISSUE THREAD

**Issue by rhc54** [open-mpi/mtt#696]
When I hit an error in executing the Python client, the mttresults.txt file contains the following (after output from various stages):
```
	 ERROR (stderr)
	     P
	     r
	     i
	     o
	     r
	      
	     d
	     e
	     p
	     e
	     n
	     d
	     e
	     n
	     t
	      
	     s
	     t
	     e
	     p
	      
	     f
	     a
	     i
	     l
	     e
	     d
	      
	     -
	      
	     c
	     a
	     n
	     n
	     o
	     t
	      
	     p
	     r
	     o
	     c
	     e
	     e
	     d
```
We obviously aren't handling the returned error output quite correctly.

**Comment by ribab** [comment]
Thanks Ralph I know the issue and will fix it

**Comment by ribab** [comment]
The issue with this is that every single plugin that has an error case fills stderr with a string, but TextFile.py is only supporting list-style stderr

My proposed fix is to fix this in sequential.py, and convert all stderrs to lists after plugin execution
