### ISSUE TITLE
doxygen pages provided via open-mpi.github.io differ from jagaskak.github.io

### ISSUE THREAD

**Issue by beardeddog** [open-mpi/mtt#705]
the doxygen at 
  https://open-mpi.github.io/mtt/html/index.html 

is not the same as Akshaya's doxygen at 
  https://jagaskak.github.io/mtt/html/index.html

the main page content, modules and classes tabs are missing

**Comment by rhc54** [comment]
Sorry - i was looking at the wrong place. Looks like doxygen failed to run properly

**Comment by ggouaillardet** [comment]
doxygen emits a bunch of error messages such as

>   File "/home/travis/virtualenv/python3.6.3/bin/doxypy.py", line 414, in <module>
>     main()
>   File "/home/travis/virtualenv/python3.6.3/bin/doxypy.py", line 411, in main
>     fsm.parseFile(filename)
>   File "/home/travis/virtualenv/python3.6.3/bin/doxypy.py", line 366, in parseFile
>     self.parseLine(line.rstrip('\r\n'))
>   File "/home/travis/virtualenv/python3.6.3/bin/doxypy.py", line 379, in parseLine
>     self.__flushBuffer()
>   File "/home/travis/virtualenv/python3.6.3/bin/doxypy.py", line 212, in __flushBuffer
>     print >>self.outstream, "\n".join(self.output)
> TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'. Did you mean "print(<message>, file=<output_stream>)"?


The root cause could be a busted python environment (I arbitrarily chose python 3.6)
@beardeddog are you generating the doc for Akshaya from travis ? which python version is used ?

**Comment by ggouaillardet** [comment]
it seems `doxypy.py` only works correctly with python 2.

I updated #711 in order to generate the documentation with python 2.7

**Comment by ggouaillardet** [comment]
my doc is available at http://ggouaillardet.github.io/mtt/html/index.html

**Comment by rhc54** [comment]
Thanks @ggouaillardet - good catch!

**Comment by beardeddog** [comment]
@ggouaillardet, yes this looks good, I will close this issue
