### ISSUE TITLE
Cannot checkout gh-pages branch on a Mac/case-insensitive filesystem

### ISSUE THREAD

**Issue by jsquyres** [open-mpi/mtt#714]
I notice that the `gh-pages` branch has some filenames that are identical, aside from their case:

```
$ find . | fgrep -i namespaceharasser.
./latex/namespaceharasser.tex
./latex/namespaceHarasser.tex
./html/namespaceharasser.html
./html/namespaceHarasser.html
```

This creates problems if you check out `gh-pages` on a Mac with its default case-insensitive filesystem.

I did a few quick searches in the code base and could not easily figure out if the namespaces `harasser` and `Harasser` are actually different or are just typos in the documentation.

It would be nice if the `gh-pages` branch could be made accessible on a Mac.

**Comment by rhc54** [comment]
I'm afraid I couldn't see where that gets generated myself - @Jagaskak can you perhaps take a look when you have a minute?

**Comment by Jagaskak** [comment]
@rhc54 Sure I can look into it.

**Comment by DebRez** [comment]
This should fix the problem: In the Doxyfile in gh-pages branch the case_sense_names is set to yes. Should be changed to no.

/# If the CASE_SENSE_NAMES tag is set to NO then doxygen will only generate file
/# names in lower-case letters. If set to YES, upper-case letters are also
/# allowed. This is useful if you have classes or files whose names only differ
/# in case and if your file system supports case sensitive file names. Windows
/# and Mac users are advised to set this option to NO.
/# The default value is: system dependent.

CASE_SENSE_NAMES       = YES

**Comment by DebRez** [comment]
CASE_SENSE_NAMES was set to NO but at some previous time was set to YES and the files with capital letters are still present.  It would be best if the html and latex directories were removed before building new documentation to prevent old files from hanging around.

**Comment by DebRez** [comment]
Looking at this more. There are over 800 files with capital letters in the gh-pages mtt/html directory alone. Deleting them manually would be very difficult and time consuming.  Would anyone mind if a did a one time delete of the entire html and latex directories so it can be built with only the case insensitive file names? @jsquyres @rhc54 @Jagaskak 

I still have concerns about never clearing out these directories when new documentation is built.  It could get filled up again with old, outdated docs.

**Comment by jsquyres** [comment]
I'm not sure how the documentation is generated, but if it always generates a full set, you could probably do something like this:

* `git rm -rf` the entire documentation directory
* generate a new set of files
* `git add` the entire documentation directory
* `git commit` the entire documentation directory

This will:

* Add all new files (that were created when the documentation was re-generated)
* Remove all old files (i.e., that weren't re-created when the documentation was re-generated)
* Effectively leave unchanged files alone

**Comment by ribab** [comment]
I don't mind cleaning out old auto-generated docs. Either way, the docs we see online should look the same. The source will look cleaner if we clean though.

**Comment by DebRez** [comment]
I have pushed the gh-pages branch to my DebRez repo. I have removed the entire html and latex directories. Travis will run doxygen again when a new commit is done on master and repopulate those files with the new case insensitive versions. How do I update the open-mpi/mtt gh-pages branch? @hppritcha
