### ISSUE TITLE
pymtt crashing with compiler UnicodeEncodeError

### ISSUE THREAD

**Issue by DebRez** [open-mpi/mtt#724]
Need to add try, except to Logger.py verbose_print method

**Comment by PeterGottesman** [comment]
Related to #680?

**Comment by DebRez** [comment]
No, the compiler is throwing the error, not our code.

**Comment by PeterGottesman** [comment]
Would you mind pasting in the backtrace that python outputs? If for no other reason it will be helpful if the error recurs somewhere else in the codebase.
