### ISSUE TITLE
add the scratchdir default to ./mttscratch back

### ISSUE THREAD

**Issue by beardeddog** [open-mpi/mtt#737]
We have a number of tests that don't specify the `scratchdir` in the ini file nor specify the `scratchdir` form from the command line, and rely on the default value for `scratchdir`.

**Comment by DebRez** [comment]
I am trying to duplicate your issues - will keep on it tomorrow. Can't seem to replicate the problem.
@beardeddog

**Comment by ribab** [comment]
https://github.com/open-mpi/mtt/blob/1be89911d4d5e1d4950339f9bbf3c05ec48a9937/pyclient/pymtt.py#L85

Previous line was:
execGroup.add_argument("--scratch-dir", dest="scratchdir", default="./mttscratch",

Now line is:
execGroup.add_argument("--scratch-dir", dest="scratchdir", default=None,


There is now no default scratchdir, so if we don't set what scratchdir to use MTT will error out weirdly

**Comment by PeterGottesman** [comment]
Yep, maybe we should add a test which ensures the default values for the INI/CLI act as expected?
I should have a little bit of time over the next few weeks, so if it would be useful I can work that and/or on some of the tests defined in `tests/bat/README.bat.txt`

**Comment by DebRez** [comment]
The default scratchdir is set in DefaultsMTTDefaults.py.  When it was set in pymtt.py it could not be changed to another name because that is the command line default. I just did a new git clone on my system of mtt master and again everything is working.  Please check yours again.
@beardeddog
