### ISSUE TITLE
--scratchdir at the command line should take precedence over scratchdir in an ini file

### ISSUE THREAD

**Issue by beardeddog** [open-mpi/mtt#739]
It would seem that we need to make sure there is some precedence on setting `scratchdir`. 

I would suggest that 
`command line` takes precedence over `ini file` setting 
`ini file` settings take precedence over `default values`

**Comment by DebRez** [comment]
I have rechecked all three ways of setting the scratch directory, it works for me.  git pull on MTT master shows 'Already up to date'.  If I have a different name on command line using --scratch-dir newname it takes precedence over the .ini file scratch = or scratchdir = .  I don't know what else to check. 
 @beardeddog
