### ISSUE TITLE
MTT_ARGS needs to be implemented

### ISSUE THREAD

**Issue by DebRez** [open-mpi/mtt#742]

**Comment by beardeddog** [comment]
I guess I don't know what this means, can you tell me more?

**Comment by DebRez** [comment]
Old Issue 718. I tried using it to add --no-reporter but it was not working.

**Comment by beardeddog** [comment]
so `--no-reporter` sets the dest **reporter** to **true**, and if I dump the args after line 159 in pymtt.py, I get

`args: Namespace(basedir=None, clean=False, clean_after=False, cmdtime=False, debug=False, default_make_options='-j10', description=None, dryrun=False, duration=None, env_module_wrapper=None, executor=None, extraverbose=False, harass_join_timeout=None, harass_stop_scripts=None, harass_trigger_scripts=None, ignoreloadpatherrs=False, ini_files=[['/opt/hit/seth/bat/negative.ini']], listplugins=None, listsections=False, liststageoptions=None, listtoolmodules=None, listtooloptions=None, listtools=False, listutilmodules=None, listutiloptions=None, listutils=False, logfile=None, loopforever=False, plugindir=None, ` **reporter=True** `, scratchdir='/tmp', sectime=True, section=None, skipsections=None, stop_on_fail=False, submit_group_results=True, time=False, trial=False, verbose=True, version=False)`

but I don't see anywhere where we do anything with that, so I think this is a problem with the reporter plugins.

**Comment by DebRez** [comment]
Your right - it is parsing correctly in pymtt.py I will open a new issue when I narrow down the problem.
