### ISSUE TITLE
--no-reporter only works from the command line.

### ISSUE THREAD

**Issue by DebRez** [open-mpi/mtt#744]
when I add 
export MTT_ARGS="--verbose --no-reporter"
to my .bash_profile only verbose works, data is sent to the reporter. LANL_DSR

**Comment by beardeddog** [comment]
I don't think the `--no-reporter` argument works at all, from the command line or from `MTT_ARGS`.

**in fact I would like to remove it completely and just have people use the `--skip-sections` argument.**

Maybe `--skip-sections` should be enhanced to support wild cards, so you could do something like
  `--skip-sections="Reporter*"`
to skip all Reporter sections like `--no-reporter` was intended to do.

Opinions?

**Comment by rhc54** [comment]
I'd agree with that change - I see no need for a special option to skip the Reporter sections. Adding the wildcard is a good idea.
