### ISSUE TITLE
MiddlewareBuild needs better check.

### ISSUE THREAD

**Issue by DebRez** [open-mpi/mtt#745]
If MiddlewareGet folder has the extracted tarball partially built from a previous run and the 'configure' file exists - on the next run MiddlewareBuild will consider it fully built and return. This will cause MTT to crash if the build was not finished by the first run.

/pylib/Tools/Build/Autotools.py
 217             # check if configure exists
                    cfg = os.path.join(location, "configure")
                    if os.path.exists(cfg):
                        # good enough
                        testDef.logger.verbose_print("As-Is location " + location + " has configure present")
                        log['status'] = 0
                        return

**Comment by rhc54** [comment]
Yeah, that isn't an adequate check
