### ISSUE TITLE
Handle TypeError in IUDatabase.py

### ISSUE THREAD

**Issue by DebRez** [open-mpi/mtt#753]
When MTT is run without allocating nodes we get the following error:
=======================================
Exception was raised: <type 'exceptions.TypeError'> 'NoneType' object has no attribute '__getitem__'
=======================================
Traceback (most recent call last):

  File "/Users/debrezanka/sandbox/mtt/pylib/Tools/Executor/sequential.py", line 287, in execute_sections
    plugin.execute(stageLog, keyvals, testDef)

  File "/Users/debrezanka/sandbox/mtt/pylib/Stages/Reporter/IUDatabase.py", line 140, in execute
    metadata['hostname'] = "\n".join(profile['profile']['nodeName'])

TypeError: 'NoneType' object has no attribute '__getitem__'

**Comment by ribab** [comment]
This information is the "platform" in MTTDefaults, however I think this should be automatically pulled from the environment by default if it's missing

**Comment by DebRez** [comment]
Error was caused by missing [Profile:Installed] line in INI file.  I will add that it is required in my INI file writeup (see Issue #749)
