### ISSUE TITLE
Improve Verbose output

### ISSUE THREAD

**Issue by DebRez** [open-mpi/mtt#755]
Add status at end of each section to verbose output.  Improve use of verbose output to help with debugging.

**Comment by DebRez** [comment]
Note: this can be added at the end of each section as the sequential executor runs.

**Comment by ribab** [comment]
Hey Deb, I'm going to look into your suggestions and add my own. They look very good -- I like this one especially

**Comment by ribab** [comment]
More to this issue:

- [ ] Status at the end of each section
- [ ] Marker for start and end of test run, displaying what INI file was used
- [ ] Status at end of test run
