### ISSUE TITLE
MTT Append to INI File

### ISSUE THREAD

**Issue by ribab** [open-mpi/mtt#769]
This feature is to allow MTT to append an INI file to the end (or beginning) of another INI file before parsing and running that INI file.

This doesn't include any modifying of INI files. The appending is done in cache before parsing INI file.

An example of where this might be used is this:

`/opt/mtt/pyclient/pymtt.py --verbose   --append_ini=/etc/mtt/default.ini   /path/to/test.ini`

default.ini might include some default sections all tests should execute, like this:

```
# Don't run any test until sanity-check passes
[Profile:SanityCheck]
plugin = Shell
command = /path/to/sanity_check.sh

# All tests need to report XML format
[Reporter:JUnitXML]
plugin = JUnitXML
file = ${ENV:TEST_NAME}.xml

# All tests write to database
[Reporter:IUDatabase]
plugin = IUDatabase
server = ....
etc = ....
```

**Comment by DebRez** [comment]
can't this be accomplished using cat?
cat /etc/mtt/default.ini /path/to/test.ini | /opt/mtt/pyclient/pymtt.py --verbose
That is how it is described in the ini file samples.
@ribab

**Comment by ribab** [comment]
Actually I recently learned that MTT already supports this. @noahv discovered that you can call multiple ini files and all the sections will be played together

```
pymtt.py --verbose file1.ini file2.ini
```
