### ISSUE TITLE
Doxygen for open-mpi MTT doesn't show everything

### ISSUE THREAD

**Issue by ribab** [open-mpi/mtt#772]
Related to #705 

Link to Github Pages https://open-mpi.github.io/mtt/

Doxygen for open-mpi github pages seems to be broken without all the features.

**Comment by DebRez** [comment]
Here are some issues I found working on this. The system building the doxygen documentation needs to be running python 2.7, have Graphviz installed (sh: dot: command not found), have Tex installed (sh: epstopdf: command not found), and have doxypypy installed (sh: doxypypy: command not found).

**Comment by DebRez** [comment]
Some options to fix these errors are to change settings in the Doxyfile. Do we need to generate the latex files? Do we need the graphics Graphviz produces? I would also suggest changing the CASE_SENSE_NAMES setting to NO for mac compatibility.

**Comment by DebRez** [comment]
Another issue with adding .ini files as custom extensions:
Adding custom extension mapping: .ini will be treated as language python
Causing errors - invalid syntax.  

I am very close to having a working Doxyfile by making the following changes:
Added doxypypy to environment requirements 
Doxyfile
CASE_SENSE_NAMES = YES
GENERATE_LATEX = NO
HAVE_DOT = NO
EXTENSION_MAPPING =             (nothing, was ini=Python)
INPUT =    ../pyclient ../pylib        (removed ../samples)
FILE_PATTERNS = *.c *.py             (removed *.ini)
