### ISSUE TITLE
Move allocatecmd and deallocatecmd into their own plugin

### ISSUE THREAD

**Issue by ribab** [open-mpi/mtt#800]
> Here is the code I am using to use srun in an salloc with Open MPI. Starts around line 443 of SLURM.py.  Will this interfere with anyone else's use case? It also makes SLURM.py more specific rather than making it more general. @ribab 
>     
>         # Add support for srun in --no-shell allocation
>         if self.allocated and (cmds['command'] == 'srun') and ("--job-name" in cmds['allocate_cmd']
>             parseAllocate_cmd = cmds['allocate_cmd'].split()
>             for word in parseAllocate_cmd:
>                 word = word.strip()
>                 if '--job-name' in word:
>                     jobname = word[11:]
>             jobid = int(subprocess.check_output(['squeue', '--noheader', '--format', '%i', '--name'
>             cmdargs.append('--jobid=%d' % (jobid))
> 
> _Originally posted by @DebRez in https://github.com/open-mpi/mtt/issues/771#issuecomment-448356945_

This will only impact others if they are using SLURM plugin with a command that doesn't support **"--jobid"** switch, and are using **allocate_cmd**.  In this case they will have a syntax error that might be difficult to debug. I'm not sure if this corner case would ever come up, but it might

Maybe it makes more sense if we do allocate_cmd and deallocate_cmd in separate stages that use a plugin that parses the jobid, and reference them using the log like so:

```
[TestRun:allocatecmd]
plugin = SallocNoShell
allocate = true
job_name = thisjob
# returns ${LOG:TestRun_allocatecmd.jobid}

[TestRun:slurm]
plugin = Slurm
...
options = --jobid=`${LOG:TestRun_allocatecmd.jobid}`

[TestRun:deallocatecmd]
plugin = SallocNoShell
deallocate = true
jobid = ${LOG:TestRun_allocatecmd.jobid}
```

What do you think? @DebRez

**Comment by DebRez** [comment]
The current code requires that the command used is srun which does support --jobid so I think it should be ok the way it is.
if self.allocated **and (cmds['command'] == 'srun')** and ("--job-name" in cmds['allocate_cmd']
        parseAllocate_cmd = cmds['allocate_cmd'].split()

The deallocate scancel uses the --job-name so that is not an issue.

@ribab

**Comment by ribab** [comment]
Maybe if the code checks whether `--jobid=` is not already in cmdargs. That might satisfy the corner case where someone using MTT wants to use `--jobid` in their srun options. 

Like so:

    # Add support for srun in --no-shell allocation
    if self.allocated and (cmds['command'] == 'srun') and ("--job-name" in cmds['allocate_cmd'] \
                and '--jobid=' not in ' '.join(cmdargs):

        parseAllocate_cmd = cmds['allocate_cmd'].split()
        for word in parseAllocate_cmd:
            word = word.strip()
            if '--job-name' in word:
                jobname = word[11:]
        jobid = int(subprocess.check_output(['squeue', '--noheader', '--format', '%i', '--name'
        cmdargs.append('--jobid=%d' % (jobid))
