### ISSUE TITLE
MTT Cherrypy Server Setup Problems

### ISSUE THREAD

**Issue by DebRez** [open-mpi/mtt#802]
When following the wiki I encountered the following problems. 
**Set Up Database**
2.) psql -U USERNAME -d DBNAME -f /opt/mtt/server/sql/schemas-v3.sql
* psql:/Users/debrezanka/sandbox/mtt/server/sql/schemas-v3.sql:249: NOTICE:  table "mpi_install" does not exist, skipping
* psql:/Users/debrezanka/sandbox/mtt/server/sql/schemas-v3.sql:368: NOTICE:  table "test_build" does not exist, skipping
* psql:/Users/debrezanka/sandbox/mtt/server/sql/schemas-v3.sql:620: NOTICE:  table "test_run" does not exist, skipping
4.) psql -U USERNAME -d DBNAME -f /opt/mtt/server/sql/summary/summary_trigger.sql
*  psql:/Users/debrezanka/sandbox/mtt/server/sql/summary/summary_trigger.sql:5: ERROR:  language "plpgsql" already exists
7.) psql -U USERNAME -d DBNAME -f /opt/mtt/server/sql/schemas-indexes.sql
* psql:/Users/debrezanka/sandbox/mtt/server/sql/schemas-indexes.sql:14: NOTICE:  index "idx_submit_http_username" does not exist, skipping
* psql:/Users/debrezanka/sandbox/mtt/server/sql/schemas-indexes.sql:46: NOTICE:  index "idx_test_names_test_suite_id" does not exist, skipping

**Comment by DebRez** [comment]
**Set Up Server**
mtt/server/php/cherrypy/bin/mtt_server_install.py  and mtt_server_service.py have not been futurized and are not usable with python 3.

**Comment by DebRez** [comment]
**Set Up Server** continued.  Some concerning messages when setting up the environment with mtt/server/php/cherrypy/bin/mtt_server_install.py

Already using interpreter /Users/debrezanka/anaconda2/envs/MTTEnv/bin/python
New python executable in /Users/debrezanka/sandbox/mtt/server/php/cherrypy/src/env/bin/python
copying /Users/debrezanka/anaconda2/envs/MTTEnv/bin/python => /Users/debrezanka/sandbox/mtt/server/php/cherrypy/src/env/bin/python
copying /Users/debrezanka/anaconda2/envs/MTTEnv/bin/../lib/libpython2.7.dylib => /Users/debrezanka/sandbox/mtt/server/php/cherrypy/src/env/lib/libpython2.7.dylib
Installing setuptools, pip, wheel...done.
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting CherryPy==8.9.0 (from -r src/mtt_server_requirements.txt (line 3))
/Users/debrezanka/sandbox/mtt/server/php/cherrypy/src/env/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:354: SNIMissingWarning: An HTTPS request has been made, but the SNI (Server Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  SNIMissingWarning
/Users/debrezanka/sandbox/mtt/server/php/cherrypy/src/env/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:150: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
/Users/debrezanka/sandbox/mtt/server/php/cherrypy/src/env/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:150: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
/Users/debrezanka/sandbox/mtt/server/php/cherrypy/src/env/lib/python2.7/site-packages/pip/_vendor/urllib3/util/ssl_.py:150: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecurePlatformWarning
cp: illegal option -- s

**Comment by beardeddog** [comment]
We are using the docker containers as described in mtt/server/docker/
Have had no issues get that up and running

**Comment by DebRez** [comment]
**Set Up Server** continued.  
The virtual environment I was in seems to have been wiped out by the above commands. There should be some kind of protection from that.  I added a step to the wiki mentioning it before the call to run 
mtt/server/php/cherrypy/bin/mtt_server_install.py.  

Sorry this is going on and on. I just want to document everything so it can be tracked.

**Comment by DebRez** [comment]
@beardeddog  should I not be using this wiki then? are there other instructions somewhere?
Thanks

**Comment by beardeddog** [comment]
@DebRez I don't know what you should use ... this is just what we are using as it fit in nicely with other containers we use.  In `mtt/server/docker/` there is a readme file, that is what I followed.

**Comment by DebRez** [comment]
Thanks
