### ISSUE TITLE
Inaccurate documentation tips_and_tricks

### ISSUE THREAD

**Issue by DebRez** [open-mpi/mtt#806]
https://open-mpi.github.io/mtt/pages/tips_and_tricks.html

The Compiler Configuration section is all perl based stuff. Need to document current way env vars are set in ini files. 

Maybe we should implement something like this if we haven't already->

MPI Install Errors
Sometimes MTT finds a problem in a middleware install, but a human wants to go examine it manually. When MTT installs a middleware under its scratch tree, it will automatically drop two files – one for sh-flavored shells and one for csh-flavored shells – that set the PATH and LD_LIBRARY_PATH to get to the middleware install. The exact location of these files depends on the section names in your INI file and the exact version number of the MPI in question. Specifically, these files will be in:

<patch to your scratch>/installs/<MPI Get name>/<MPI Install name>/<MPI version number>/mpi_installed_vars.sh
<patch to your scratch>/installs/<MPI Get name>/<MPI Install name>/<MPI version number>/mpi_installed_vars.csh
Hence, you can source these files like this (assuming a csh-flavored shell):

shell% cd <patch to your scratch>/installs/<MPI Get name>/<MPI Install name>/<MPI version number>
shell% source mpi_installed_vars.csh
Mpicc, mpirun, etc. will then be in your PATH, and the appropriate libraries will be in your LD_LIBRARY_PATH. Additionally, the environment variable MPI_ROOT will be set that points to the top-level installation directory for the middlewareBuild. This is useful with Open MPI’s --prefix option to mpirun, for example. Note that all the files related to the testing of that MPI are under this tree – the source tree, the tests, etc. So you can go examine the entire test – not just put the MPI in question in your path.

**Comment by hppritcha** [comment]
opened issue #890 to better document the enhancement request in this issue's description.

**Comment by hppritcha** [comment]
closed via #888
