### ISSUE TITLE
Problem getting MTT Reporter working in a virtual machine

### ISSUE THREAD

**Issue by DebRez** [open-mpi/mtt#815]
I have followed the directions in mtt/server/docker/README.docker.txt to set up the MTT Reporter on a Centos 7 virtual machine (running on macOS High Sierra using VMWare Fusion). I can see the cherrypy server is running as follows:
###### curl -H "Content-Type: application/json" -X POST -d '{"data" : [ {"bitness": 0, "endian": "test", "vpath_mode": "test", "platform_hardware": "test", "platform_type": "test", "os_name": "test", "os_version": "test", "compiler_name": "test", "compiler_version": "test", "mpi_name": "test", "mpi_version": "test", "configure_arguments": "test", "start_timestamp": "Mon Jan 1 00:00:00 2000", "duration": "0 Seconds", "result_message": "test", "test_result": 0, "exit_value": 0, "merge_stdout_stderr": 0, "result_stderr": "test"} ], "metadata" : {"client_serial": 12345, "hostname": "test.test.com", "local_username": "test", "mtt_client_version": "4.0a1", "phase": "MPI Install", "platform_name": "triton", "trial": 1}}' http://172.31.0.3:9080/submit --user mtt:mttuser
Which returns:
###### {"status": 0, "submit_id": 1, "status_message": "Success", "ids": [{"mpi_install_id": 1}]}
And I can see something in my browser on the virtual machine:
![Screen Shot 2019-05-07 at 2 05 13 PM](https://user-images.githubusercontent.com/7883609/57329524-2c95c780-70d1-11e9-8097-b15b2f97e395.png)
The problem is that when I do a mtt run on the virtual machine IUDatabase.py can't connect to the database. I get 
###### Error: Unable to get a client serial (rtn=-1)

**Comment by DebRez** [comment]
Here is the url I am using to connect - similar to connecting to mtt.open-mpi.org
url = http://172.31.0.3:9080/submit/cpy/api/

Leaving out the username and password ->The contents of my mtt_server.cfg file are:
[server]
socket_host = 172.31.0.3
socket_port = 9080
url_docroot = http://your.domain/mtt/
[logging]
log_level=DEBUG
log_file=log/mtt.log
[pg_v3]
type= postgres
dbname= mtt
server= 172.31.0.2
port= 5432

This was automagically configured by Dockerfile.cherrypy.

**Comment by DebRez** [comment]
Here is the output from the logs.
[log_output.txt](https://github.com/open-mpi/mtt/files/3154443/log_output.txt)

**Comment by DebRez** [comment]
Is there a way to see the data that the IUDatabase reporter is sending to the server? @ribab @noahv

**Comment by hppritcha** [comment]
@rhc54 is there a logging/debugging mechanism/option in the IUdatabase reporter to log its messages to the server in a file?

**Comment by rhc54** [comment]
Sorry for the long, unpardonable delay - been catching up to the inbox. Looking at that plugin, I see:
```python
self.options['debug_filename'] = (None, "Debug output file for server interaction information")
self.options['keep_debug_files'] = (False, "Retain reporter debug output after execution")
self.options['debug_server'] = (False, "Ask the server to return its debug output as well")
self.options['debug_screen'] = (False, "Print debug output to screen")
```
I would think those might help?

**Comment by noahv** [comment]
Hi Deb,

To debug this you can connect to the cherrypy docker container and look at the logs:

`docker exec -it mttdb-cherrypy bash`

The logs are found in /opt/mtt/server/php/cherrypy/log.

You can combine this with stepping through the IUDatabase plugin:

`MTT_HOME=/home/noah/mtt python -m pdb /opt/mtt/pyclient/pymtt.py --verbose ./negative.ini`

**Comment by noahv** [comment]
Debug is ongoing but the here are patches to the code base if you want to pursue the issue:

```
diff --git a/pylib/Stages/Profile/DefaultProfile.py b/pylib/Stages/Profile/DefaultProfile.py
index dcba4055..baaae952 100644
--- a/pylib/Stages/Profile/DefaultProfile.py
+++ b/pylib/Stages/Profile/DefaultProfile.py
@@ -30,12 +30,12 @@ class DefaultProfile(ProfileMTTStage):
         # initialise parent class
         ProfileMTTStage.__init__(self)
         self.options = {}
-        self.options['kernelName'] = (True, "Kernel name", ["uname", "-s"])
-        self.options['kernelRelease'] = (True, "Kernel release string", ["uname", "-r"])
-        self.options['kernelVersion'] = (True, "Kernel version string", ["uname", "-v"])
-        self.options['machineName'] = (True, "Machine name", ["uname", "-m"])
-        self.options['processorType'] = (True, "Processor type", ["uname", "-p"])
-        self.options['nodeName'] = (True, "Node name", ["uname", "-n"])
+        self.options['kernelName'] = (None, "Kernel name", ["uname", "-s"])
+        self.options['kernelRelease'] = (None, "Kernel release string", ["uname", "-r"])
+        self.options['kernelVersion'] = (None, "Kernel version string", ["uname", "-v"])
+        self.options['machineName'] = (None, "Machine name", ["uname", "-m"])
+        self.options['processorType'] = (None, "Processor type", ["uname", "-p"])
+        self.options['nodeName'] = (None, "Node name", ["uname", "-n"])
         return

     def activate(self):
```

```
diff --git a/pylib/Stages/Reporter/IUDatabase.py b/pylib/Stages/Reporter/IUDatabase.py
index eebdd2c4..6b41b357 100755
--- a/pylib/Stages/Reporter/IUDatabase.py
+++ b/pylib/Stages/Reporter/IUDatabase.py
@@ -125,9 +125,9 @@ class IUDatabase(ReporterMTTStage):
             www_auth = None

         # Get a client serial number
-        client_serial = self._get_client_serial(s, self.cmds['url'], www_auth)
-        if client_serial < 0:
-            print("Error: Unable to get a client serial (rtn=%d)" % (client_serial))
+        ##client_serial = self._get_client_serial(s, self.cmds['url'], www_auth)
+        ##if client_serial < 0:
+        ##    print("Error: Unable to get a client serial (rtn=%d)" % (client_serial))

         headers = {}
         headers['content-type'] = 'application/json'
@@ -136,7 +136,7 @@ class IUDatabase(ReporterMTTStage):

         profile = testDef.logger.getLog('Profile:Installed')
         metadata = {}
-        metadata['client_serial'] = client_serial
+        ##metadata['client_serial'] = client_serial
         metadata['hostname'] = "\n".join(profile['profile']['nodeName'])
         metadata['http_username'] = self.cmds['username']
         metadata['local_username'] = pwd.getpwuid(os.getuid()).pw_name
```

**Comment by noahv** [comment]
Here is my .ini as well:

```
diff --git a/tests/bat/negative.ini b/tests/bat/negative.ini
index fc2463df..df115a33 100644
--- a/tests/bat/negative.ini
+++ b/tests/bat/negative.ini
@@ -6,6 +6,10 @@
 scratch = mttscratch
 description = MTT negative BAT test

+
+[Profile:Installed]
+plugin = DefaultProfile
+nodeName = toad
 #======================================================================
 # Test get phases - get the tests that the
 # target software will run.
@@ -24,6 +28,17 @@ parent = TestGet:Negative
 command = ./negative.sh
 fail_test = negative.sh

+[Reporter: IU database]
+plugin = IUDatabase
+realm = OMPI
+organization = Intel
+hostname = toad
+#platform = DSR-CentOS7-VM
+#url = https://mtt.open-mpi.org/submit/cpy/api/
+url = http://172.31.0.3:9080/submit
+username = mtt
+password = mttuser
+
 #======================================================================
 # Reporter phase
 #======================================================================
@@ -36,3 +51,4 @@ plugin = TextFile
 [Reporter:JunitXML]
 plugin = JunitXML
 filename = negative.xml
```

**Comment by noahv** [comment]
Access logs are showing the following 404 when using requests instead of curl

```
172.31.0.1 - - [16/May/2019:14:39:17] "POST /submit HTTP/1.1" 200 90 "" "curl/7.37.0"
172.31.0.1 - - [16/May/2019:14:41:45] "POST /submit/submit HTTP/1.1" 404 1465 "" "python-requests/2.9.1"
```

**Comment by rhc54** [comment]
@noahv Is there some reason the debug params in IUDatabase are not being used? They seem to be aimed at precisely this type of debugging. Are they not working, or not sufficient, or...?

**Comment by noahv** [comment]
Looks like the issue was a malformed url in the .ini file plus the patches above.  Don't include the "submit" in the url.  That gets us past the cherrypy 404 error.

**Comment by noahv** [comment]
I agree as part of the development work for this plugin the debug params should be tested and verified to help for a case such as this one.

**Comment by rhc54** [comment]
@noahv Let me explain the reason for my question. In the past, we have had continual problems where the only way someone could debug their ini file was to get someone with admin permissions to login to the server and dig out the debug logs as you are now doing. It was painful and intrusive as everything funneled into one person (@jjhursey).

Part of the rationale for those debug options was to give the user access to the information that is otherwise being dumped into logs on the server, which only the server admin can access. This would let users debug their own ini files without having to impose on an admin.

HTH

**Comment by DebRez** [comment]
@rhc54 When I run using the 
self.options['debug_filename'] = (None, "Debug output file for server interaction information")
self.options['keep_debug_files'] = (False, "Retain reporter debug output after execution")
self.options['debug_server'] = (False, "Ask the server to return its debug output as well")
self.options['debug_screen'] = (False, "Print debug output to screen")

All except debug_filename cause a 'ValueError: invalid literal for int() with base 10: 'True'' in the TestDef.py __convert_value method.  debug_filename does nothing at all. So, we need to implement these. Maybe make this a new Issue?

I have the database running ok now using http://localhost:9080 as the url.

**Comment by rhc54** [comment]
Yeah, a new issue makes sense - I was afraid we hadn't implemented those yet.
