### ISSUE TITLE
Error getting IBM tests - python client

### ISSUE THREAD

**Issue by DebRez** [open-mpi/mtt#816]
The last time I had a successful MTT run was with the ompi-master 05/20/19. Since then I am getting the error Exception was raised: <type 'exceptions.OSError'> [Errno 2] No such file or directory:    scratch/TestGet_IBM/ompi-tests/ibm

This is happening on different systems and I have made no changes to my .ini file.

I can git clone the ompi-tests repository manually and the IBM folder transfers over fine so it seems to be a problem with MTT.  Is anyone else seeing this problem?

**Comment by DebRez** [comment]
Here is the TestGet section of my INI file
[ASIS TestGet:IBM]
plugin = Git
url =  git@github.com:open-mpi/ompi-tests
subdir = ibm
parent = MiddlewareBuild:OMPIMaster

**Comment by DebRez** [comment]
Here is the output from the TestGet:
========================================================================
START EXECUTING [ASIS TestGet:IBM] start_time=2019-05-27 21:57:20.591756
========================================================================
OPTIONS FOR SECTION: ASIS TestGet:IBM
  plugin = Git
     url = git@github.com:open-mpi/ompi-tests
  subdir = ibm
  parent = MiddlewareBuild:OMPIMaster
Executing plugin Git
Git Execute
Working repo git@github.com:open-mpi/ompi-tests
Working final repo git@github.com:open-mpi/ompi-tests
ExecuteCmd start: git clone git@github.com:open-mpi/ompi-tests
stdout: Cloning into 'ompi-tests'...
stderr: Checking out files:   5% (600/10030) 
Checking out files: 100% (10030/10030), done.
ExecuteCmd done
Fetch CMD: merge_stdout_stderr stderr_save_lines pr scratchdir modules_unload pl
atform subdir branch pwfile asis username description parent time password url s
tdout_save_lines modules trial modules_swap executor organization
LOGGING results for ASIS TestGet:IBM
DONE EXECUTING [ASIS TestGet:IBM] end_time=2019-05-27 21:57:53.415520, elapsed=0:00:32.823764
STATUS OF [ASIS TestGet:IBM] IS 0

ASIS TestBuild:IBMInstalled

===================================================================================
START EXECUTING [ASIS TestBuild:IBMInstalled] start_time=2019-05-27 21:57:53.415800
===================================================================================
OPTIONS FOR SECTION: ASIS TestBuild:IBMInstalled
               parent = TestGet:IBM
  merge_stdout_stderr = 1
    stderr_save_lines = 100
           middleware = MiddlewareBuild:OMPIMaster
          autogen_cmd = ./autogen.sh
         make_options = -j 2
    configure_options = CC=mpicc CXX=mpic++ FC=mpifort F77=mpifort
Executing plugin DefaultTestBuild
DefaultTestBuild
Autotools Execute
Unknown conversion required for 100
ExecuteCmd start: icc -c spastic.c
ExecuteCmd done
ExecuteCmd start: icc --version
stdout: icc (ICC) 18.0.5 20180823
stdout: Copyright (C) 1985-2018 Intel Corporation.  All rights reserved.
stdout: 
ExecuteCmd done
{'status': 0, 'version': u'icc (ICC) 18.0.5 20180823', 'compiler': 'intel'}
mpi_info already in log so skipping MPIVersion
=======================================
Exception was raised: <type 'exceptions.OSError'> [Errno 2] No such file or directory: '/yellow/usr/projects/hpctools/drezanka/fogDir/mtt/masterWalloc_scratch/TestGet_IBM/ompi-tests/ibm'

**Comment by noahv** [comment]
Hi Deb, I was able to reproduce this issue.  Very strange.  Still debugging it...

**Comment by noahv** [comment]
This recent patch causes this issue:

commit f649e180595cf1f66de9156929dff16b3ffcc0d6
Author: Richard Barella <richard.t.barella@intel.com>
Date:   Thu May 2 10:45:07 2019 -0700

    Clean up middlware build directory before building

    There was a test that we had to remove mttscratch before the test can pass
    Autotools plugin wasn't cleaning up previous builds

    This patch forces the clean-up to happen if Autotools plugin is about to commence a build

    Signed-off-by: Richard Barella <richard.t.barella@intel.com>
