### ISSUE TITLE
MTT Reporter not failing correctly.

### ISSUE THREAD

**Issue by DebRez** [open-mpi/mtt#845]
A problem with OMPIMaster is causing the test build to fail.  The MTT Reporter is not displaying correctly. The MPI Install should have a Pass and the Testbuild a Fail but it is showing all zeros.
![Screen Shot 2019-08-02 at 10 49 42 AM](https://user-images.githubusercontent.com/7883609/62385822-54030180-b513-11e9-821c-0d958c495682.png)

Here is the output from the cherrypy server log mtt.log where the test build fails (this is from the aws.open-mpi.org site):

  FCLD     op_usempif08
  CCLD     ineighbor_allgather
/usr/bin/ld: op_usempif08.o: in function `somewhat_less_':
/global/u2/d/drezanka/cori/mtt/masterWalloc_scratch/TestGet_IBM/ompi-tests/ibm/collective/op_usempif08.F90:68: undefined reference to `mpi_f08_types_mp_ompi_datatype_op_ne_'
/usr/bin/ld: op_usempif08.o: in function `MAIN__':
/global/u2/d/drezanka/cori/mtt/masterWalloc_scratch/TestGet_IBM/ompi-tests/ibm/collective/op_usempif08.F90:172: undefined reference to `mpi_f08_types_mp_ompi_op_op_ne_'
/usr/bin/ld: link errors found, deleting executable `op_usempif08'
make[2]: *** [Makefile:2618: op_usempif08] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/global/u2/d/drezanka/cori/mtt/masterWalloc_scratch/TestGet_IBM/ompi-tests/ibm/collective'
make[1]: *** [Makefile:3075: all-recursive] Error 1
make[1]: Leaving directory '/global/u2/d/drezanka/cori/mtt/masterWalloc_scratch/TestGet_IBM/ompi-tests/ibm/collective'
make: *** [Makefile:434: all-recursive] Error 1, true
[2019-08-02 14:18:43,595] DEBUG [DB PG V3] _get_nextval(test_build_test_build_id_seq) = 1621004
[2019-08-02 14:18:43,614] DEBUG [DB PG V3] _select_insert(test_build, test_build_id) = [Insert] 1621004
[2019-08-02 14:18:43,614] DEBUG [DB PG V3] (test_build)  --- Processing: test_build = 1621004
[2019-08-02 14:18:43,614] DEBUG ----------------------- Return Values JSON (Start) ------------------
[2019-08-02 14:18:43,614] DEBUG {
    "ids": [
        {
            "test_build_id": 1621004
        }
    ],
    "status": 0,
    "status_message": "Success",
    "submit_id": 647287
}
[2019-08-02 14:18:43,614] DEBUG ----------------------- Return Values JSON (End  ) ------------------

##NOTE:
The MTT python client being used is commit 6018134342cfd5a95f97e2c6ce782179390c1bb9

**Comment by jjhursey** [comment]
For that particular submission the `test_result` submitted by the Python client was `-1`
```
ompidb=> select test_result from test_build where test_build_id = 1621004;
 test_result 
-------------
          -1
(1 row)
```
Which is why it is not showing up in the reporter. The reporter only recognizes values `[0-3]` seen here:
 * https://github.com/open-mpi/mtt/blob/master/server/php/reporter/reporter.inc#L116-L124
