### ISSUE TITLE
Most recent version of MTT failing on three different systems.

### ISSUE THREAD

**Issue by DebRez** [open-mpi/mtt#852]
MTT is failing on Fog, Trinitite and Cori systems since the most recent version was pulled. One clear error was the missing shlex import in LauncherMTTTool.py.

Pull request #851 is meant to fix this issue but the travis build is failing. The only change made was to add the missing "import shlex" statement. Can you help troubleshoot this @rhc54 ?

**Comment by rhc54** [comment]
Sure - can you give me any more info on how it is failing?

**Comment by DebRez** [comment]
I have seen several issues. The missing shlex import, ERROR (stderr) No tests found, and ERROR (stderr) Too many return codes were supplied to satisfy the number of tests expected to fail: 2:1

Here is the relevant parts of my INI file:
                 fail_tests = abort final
                 fail_timeout = max_procs
                 fail_returncodes = 1, 3

**Comment by rhc54** [comment]
How long has it been since you updated? Just want to get some idea of the change involved as those areas of the code were modified like a month or more ago, AFAIK

**Comment by DebRez** [comment]
I just updated last thursday.

**Comment by rhc54** [comment]
I was asking how long it had been before that 😄

**Comment by DebRez** [comment]
Many months

**Comment by rhc54** [comment]
wow - that might not be a good idea as it can let problems go by until it is very hard to track them down. If you are going to update that infrequently, then you probably should create some CI or nightly regression so we have a chance to catch them earlier on.

I take it those are Cray machines? What Python version are you using?

**Comment by DebRez** [comment]
python 2.7. Trinitite  and Cori are cray systems, Fog is a "commodity" system - all intel hardware.

**Comment by rhc54** [comment]
Is there anything common about those machines - e.g., they are all running under Slurm?

Can you post the full .ini section that is failing? I'd like to see what plugin is being used and the full set of options. Best I can tell: it would appear your option parser may be getting confused. Note that right now the LaunchMTTTool ignores the "fail_timeout" option - doesn't hurt to have it, but won't do anything

**Comment by DebRez** [comment]
I am getting the error "No tests found" now and it looks like the only place that line shows up is in  LauncherMTTTool.py. 

Those machines are all running under Slurm. Here is the .ini file for Fog:

[LauncherDefaults:OMPI]
plugin = SLURM
command = srun
options = -n 16 -c 4 -t 15:00
skipped = 77
merge_stdout_stderr = 1
stdout_save_lines = 100
stderr_save_lines = 100

[TestRun:IBMInstalledOMPI]
plugin = SLURM
parent = TestBuild:IBMInstalled
timeout = 600
test_dir = "collective, communicator, datatype, environment, group, info, io, pt2pt, random, topology"
-# Tests that are supposed to fail
fail_tests = abort final
fail_timeout = max_procs
-# return codes for tests that are supposed to fail. Length of fail_returncodes
-# must match length of fail_tests
fail_returncodes = 1, 3

skip_tests = init_thread_multiple comm_split_f

allocate_cmd = salloc -N 4 --qos=interactive --no-shell --exclusive --time=03:00:00 --job-name=openmpi_master
deallocate_cmd = scancel --name openmpi_master

**Comment by rhc54** [comment]
> I am getting the error "No tests found" now and it looks like the only place that line shows up is in LauncherMTTTool.py.

Correct - the plugin is telling you that it didn't find any tests, so either it isn't looking in the right place or the tests didn't get built

I'd suggest adding a debug print at the start of the `collectTests` function to see what is in the `test_list` and `test_dir` keys. I'm wondering if the quotes around the `test_dir` entry are causing a problem here.

I'd do the same wit the `fail_tests` and `fail_returncodes` options - let's see what the parser returned for you

**Comment by DebRez** [comment]
It looks like there is a problem with the fail_tests and fail_returncodes being entered just right.  We need better error messages for this. Before the Launcher redo the fail_tests had to be a list with no commas and fail_returncodes was not required.  I was able to get a successful run with 
fail_tests = abort, final
fail_returncodes = 1, 3

**Comment by rhc54** [comment]
I honestly didn't add the fail_returncodes thing - it was already there on at least one launcher plugin. I simply collected the code into one place so all plugins would have a common behavior and input deck. I'll look into making the parser a little more friendly.

I'll bet the Slurm launcher isn't providing some needed fields to the reporter - I assume you are talking about the IUDatabase plugin?

**Comment by DebRez** [comment]
Yes, I am using the IUDatabase plugin.

**Comment by DebRez** [comment]
@rhc54 The most recent version of MTT is only populating the MTT Reporter Database with MPI install and Test build results.  Tests are running and the output shows passed, failed and skipped tests but the results are not getting to the reporter.  Here is some output from my TextFile reporter:
Section: LauncherDefaults:OMPI Status: 0
        Input parameters:
                 plugin = SLURM
                 command = srun
                 options = -n 16 -c 4 -t 15:00
                 skipped = 77
                 merge_stdout_stderr = 1
                 stdout_save_lines = 100
                 stderr_save_lines = 100
        Final options:
                 merge_stdout_stderr = True
                 max_num_tests = None
                 skip_tests = None
                 test_list = None
                 hostfile = None
                 allocate_cmd = None
                 stderr_save_lines = 100
                 scratchdir = /yellow/usr/projects/hpctools/drezanka/fogDir/mtt/v40xWalloc_scratch
                 fail_timeout = None
                 modules_unload = None
                 fail_tests = None
                 platform = LANL-Fog
                 np = None
                 job_name = None
                 deallocate_cmd = None
                 skipped = 77
                 description = OpenMPI v4.0.x
                 executor = sequential
                 dependencies = None
                 test_dir = None
                 stdout_save_lines = 100
                 modules = None
                 trial = False
                 modules_swap = None
                 command = srun
                 timeout = None
                 time = False
                 organization = None
                 options = -n 16 -c 4 -t 15:00
Section: TestRun:IBMInstalledOMPI Status: 137
        Input parameters:
                 plugin = SLURM
                 parent = TestBuild:IBMInstalled
                 timeout = 600
                 test_dir = "collective, communicator, datatype, environment, group, info, io, pt2pt, random, topology"
                 fail_tests = abort:3 final:1
                 fail_timeout = max_procs
                 skip_tests = init_thread_multiple comm_split_f
                 allocate_cmd = salloc -N 4 --qos=interactive --no-shell --exclusive --time=3:00:00 --job-name=openmpi_v40x
                 deallocate_cmd = scancel --name openmpi_v40x
        Final options:
                 merge_stdout_stderr = True
                 max_num_tests = None
                 skip_tests = init_thread_multiple comm_split_f
                 test_list = None
                 hostfile = None
                 allocate_cmd = salloc -N 4 --qos=interactive --no-shell --exclusive --time=3:00:00 --job-name=openmpi_v40x
                 stderr_save_lines = 100
                 scratchdir = /yellow/usr/projects/hpctools/drezanka/fogDir/mtt/v40xWalloc_scratch
                 fail_timeout = max_procs
                 modules_unload = None
                 fail_tests = abort:3 final:1
                 platform = LANL-Fog
                 np = None
                 job_name = None
                 deallocate_cmd = scancel --name openmpi_v40x
                 skipped = 77
                 description = OpenMPI v4.0.x
                 parent = TestBuild:IBMInstalled
                 executor = sequential
                 dependencies = None
                 test_dir = "collective, communicator, datatype, environment, group, info, io, pt2pt, random, topology"
                 stdout_save_lines = 100
                 modules = None
                 trial = False
                 modules_swap = None
                 command = srun
                 timeout = 600
                 time = False
                 organization = None
                 options = -n 16 -c 4 -t 15:00
       ERROR (stderr)
             Message size 8000000000 bigger than supported by PSM2 API. Max = 4294967296
             srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
             [fg007:134617] *** An error occurred in MPI_Irecv
             [fg007:134617] *** reported by process [3605397542,1]
             [fg007:134617] *** on communicator MPI COMMUNICATOR 3 SPLIT FROM 0
             [fg007:134617] *** MPI_ERR_OTHER: known error not in list
             [fg007:134617] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
             [fg007:134617] ***    and potentially your MPI job)
             slurmstepd: error: *** STEP 251622.38 ON fg007 CANCELLED AT 2019-08-15T18:50:16 ***
             srun: error: fg009: tasks 8-11: Killed
             srun: error: fg008: tasks 4-7: Killed
             srun: error: fg010: tasks 12-15: Killed
             srun: error: fg007: tasks 0,2-3: Killed
             srun: error: fg007: task 1: Exited with exit code 16

        Tests: 569 Pass: 505 Skip: 2 Fail: 64 TimedOut: 0 

                 allgather   Status: 0 Category: PASSED
                 allgather_gap   Status: 0 Category: PASSED
                 allgatherv   Status: 0 Category: PASSED
                 allgather_in_place   Status: 0 Category: PASSED
                 allreduce   Status: 0 Category: PASSED

**Comment by rhc54** [comment]
Afraid I cannot reproduce that behavior - I just tested it again with the head of the MTT master branch and using the Slurm plugin, and everything was correctly reported to the IUDatabase:

<img width="1256" alt="image" src="https://user-images.githubusercontent.com/2440928/63192317-ba157b80-c01f-11e9-9a4f-4f73c2b15246.png">
