### ISSUE TITLE
pdb.set_trace() causes MTT to hang

### ISSUE THREAD

**Issue by DebRez** [open-mpi/mtt#860]
I am trying to use pdb to debug but when I use pdb.set_trace() in SLURM.py, LauncherMTTTool.py or sequential.py MTT just hangs. Any Ideas why?

**Comment by rhc54** [comment]
Afraid I have no idea. Does pdb handle multi-threaded apps? I wonder if the global lock gets into thread-lock as execute_cmd runs?

**Comment by rhc54** [comment]
Looking at the pdb documentation, the problem may be a factor of where you are putting the call to `pdb.set_trace`. This call just creates a "hook" that causes invocation of the CLI for the debugger - i.e., it throws you into the Python interactive interpreter. However, you are executing in a plugin, not the main code base.

I don't know if that's a factor or not, but it wouldn't surprise me if the interpreter was having trouble finding the right code location in the plugin. You might see if it hangs anytime you are trying to attach inside a plugin, or if it is only those specific plugins that are an issue.

**Comment by DebRez** [comment]
Thanks Ralph,
pdb.set_trace does work outside of the plugins. I have resolved the issue that I was trying to use pdb for.

--
Deb Rezanka
B Schedule
HPC-ENV
Office 9, 2nd floor Research Park
TA-03, Building 4200, Room 203
Los Alamos National Laboratory
