### ISSUE TITLE
python client and intel compiler issue

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/mtt#897]
Wondering if anyone's observed a problem I'm seeing trying to use the python client to test building Open MPI and tests using Intel 19.  What I'm noticing is everything runs fine through configury of Open MPI, but once the tool starts building OMPI, it just hangs.  In particular, the hang is due to the Intel ICC backend mcpcom getting stuck doing I/O to its parent icc:

```
(gdb) bt
#0  0x00007f4d0367ad44 in write () from /lib64/libc.so.6
#1  0x00007f4d0360c21d in _IO_file_write@@GLIBC_2.2.5 () from /lib64/libc.so.6
#2  0x00007f4d0360b4ff in new_do_write () from /lib64/libc.so.6
#3  0x00007f4d0360d409 in __GI__IO_do_write () from /lib64/libc.so.6
#4  0x00007f4d0360c90f in __GI__IO_file_xsputn () from /lib64/libc.so.6
#5  0x00007f4d035dfe24 in vfprintf () from /lib64/libc.so.6
#6  0x00007f4d035e8524 in fprintf () from /lib64/libc.so.6
#7  0x0000000001063eca in ?? ()
#8  0x00000000010d8852 in ?? ()
#9  0x00000000010d839c in ?? ()
#10 0x00000000010d7cbf in ?? ()
#11 0x00000000010d496b in ?? ()
#12 0x00000000010d2d4c in ?? ()
```

I'm not particularly interested in testing Intel with Open MPI using MTT, but did notice this.  It seems consistent and independent of the file system I'm using as my scratchdir.

If I configure and compile OMPI outside of MTT, things go fine - well there arer bizzillons of warning messages being spewed out because of some misuse of C11 atomics, but that's a different story.

**Comment by hppritcha** [comment]
Hmmm.  What’s expected to happen with mtt client if a process it is running is spewing lots of output to stderr?  Does it only read so many lines then stop reading more?

**Comment by hppritcha** [comment]
okay, if I

- switch to using --disable-c11-atomics in the configury, which cuts out lots of stderr output when building OMPI and
- use an older Intel compiler which doesn't complain about some long long double thing we put into the Open MPI configury for Intel

then this issue goes away.

I think the logic around the select for stdin/stdout in pylib/Utilities/ExecuteCmd.py is not able to handle a flood of warnings during an ompi compile.

**Comment by rhc54** [comment]
By default, we take all lines and output them. However, I'll be you will find that your .ini file contains a directive limiting the length of stderr and/or stdout. The OMPI ini files typically limit them to 100 lines.

**Comment by hppritcha** [comment]
I have that set for building the ompi tests but not the section for building ompi itself.

**Comment by hppritcha** [comment]
well, it would probably help to have stderr's pipe in the select call ;) fix coming shortly

**Comment by hppritcha** [comment]
looks like this was fixed in a newer commit.
