### ISSUE TITLE
cherrypy server code experiences traumas moving from python2 to python3

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/mtt#914]
The cherrypy related server code has a number of python2isms that caused the installation at mtt.open-mpi.org to start failing once that system was upgraded and python2 was no longer supported.

**Comment by hppritcha** [comment]
Actually turns out @DebRez had fixed many of the python3 problems in cherrypy but we'd not updated mtt on the mtt.openmpi.org install recently.  did that today.  still need PR #915

**Comment by hppritcha** [comment]
closed via #915 and refresh of mtt on mtt.open-mpi.org

**Comment by ribab** [comment]
How did the update go @hppritcha ?
