### ISSUE TITLE
Question/Request: Is the GitHub wiki completely outdated regarding the Python client? If so, please make this more obvious.

### ISSUE THREAD

**Issue by rohlem** [open-mpi/mtt#926]
As a newcomer, the GitHub wiki (linked in the project readme) was one of the first places I used to read up on MTT.
It features, for example, [a page with a detailed list of all funclets](https://github.com/open-mpi/mtt/wiki/INI-Funclets).

However, currently writing these expressions into the values of my test `.ini`-file, the Python client seems to take the expressions verbatim, without any processing.
[The GitHub-io-page](https://open-mpi.github.io/mtt/) never mentions them either.
There haven't been any issues or pull requests since 2017 referencing them.
Thus, I assume the Python client never supported funclets, and all references to them must be outdated information.

From this, I further assume the wiki (though containing 4 pages with "Python" in their name) is not up-to-date for current/ the Python client's behaviour.
It would be great to have some kind of guidance/hint about the state of which documentation is even worth consulting.
For example, the [main landing page](https://github.com/open-mpi/mtt/wiki) and [MTTOverview page](https://github.com/open-mpi/mtt/wiki/MTTOverview) would benefit from a disclaimer, if the wiki largely is outdated.

Obviously I am quite underinformed about this, so feel free to correct me / fill me in.

**Comment by hppritcha** [comment]
HI Rohlem,

You are correct on a number of points.  First most of the wiki pages
related to the perl code (client).

Some documentation about the python client is at
https://open-mpi.github.io/mtt/ although that is somewhat spotty.

There are wiki pages pertaining to the python client and server
infrastructure, but they were written primarily for users already familiar
with at least parts of the project.

I updated the Home wiki page to note that most of the wiki page content is
obsolete.  More drastic changes coming to make this clearer.

Note there are example ini files in samples/python folder which may be
helpful.

Howard


Am Sa., 30. Okt. 2021 um 15:53 Uhr schrieb Rohlem ***@***.***

**Comment by rohlem** [comment]
Thank you for the quick response!

> More drastic changes coming to make this clearer.

Sounds like I should keep the issue open to track this?
I think the header already helps a lot, so from my perspective feel free to close (or retitle) it however seems appropriate.

**Comment by hppritcha** [comment]
the wiki pages for the old perl client have been moved to https://github.com/open-mpi/mtt-legacy/wiki and the wiki pages for this repo have been cleaned up to only retain pages relevant to the python client.  Note some of these pages (like the ones pertaining to the MTT reporter) are the same as for the legacy perl client.
