### ISSUE TITLE
.elog files are huge

### ISSUE THREAD

**Issue by ribab** [open-mpi/mtt#937]
Originally I implemented the `*.elog` files as a way to ingest MTT output into ELK, however we haven't been using them and they are becoming a waste of space.

Does anyone mind if I disable these output files by default?

**Comment by ribab** [comment]
@hppritcha

**Comment by hppritcha** [comment]
i don't mind disabling them.

**Comment by ribab** [comment]
sounds good

**Comment by ribab** [comment]
@hppritcha I found out that these files aren't generated if you don't include certain `MTT_ELK_*` environment variables, so they actually already are disabled by default. So there is no change needed in MTT.

**Comment by hppritcha** [comment]
great!  I never used the ELK stuff so never got to see how big these files can be.
