### ISSUE TITLE
Intel test suite with Python client

### ISSUE THREAD

**Issue by sunkuamzn** [open-mpi/mtt#938]
At AWS, we currently have a legacy system running the legacy Perl client. This system runs the IBM and Intel test suites. We are trying to move a new system that uses the Python client. We've figured out how to run the IBM suite but we don't know how to run the Intel suite.

The Test build section of the config in the legacy system looks like this
```
[Test build: ibm]
test_get = ibm
save_stdout_on_success = 1
merge_stdout_stderr = 1
stderr_save_lines = 100

module = Shell
shell_build_command = <<EOT
./configure --enable-static --disable-shared
make -j 32
EOT

#----------------------------------------------------------------------
[Test build: intel]
test_get = intel
save_stdout_on_success = 1
merge_stdout_stderr = 1
stderr_save_lines = 100
module = Intel_OMPI_Tests
intel_ompi_tests_buildfile = all_tests_no_perf
intel_ompi_tests_make_arguments = -j 32
```

The Intel suite is using `module = Intel_OMPI_Tests`. From what I can tell, modules in the legacy client are plugins in the Python client. What's the equivalent plugin to build the Intel tests?

When I search for `Intel_OMPI_Tests`, there are no results in the `mtt` repo and I just see [configs using that module in `ompi-tests`](https://github.com/open-mpi/ompi-tests/search?p=1&q=Intel_OMPI_Tests)
I can’t find any code related to the `Intel_OMPI_Tests` module

The example configs for the new Python client that have the Intel tests all skip the Intel tests ([1](https://github.com/open-mpi/mtt/blob/a985719825e5377e9d558fdd968631602d0fd093/samples/python/mpitest.ini#L66-L70), [2](https://github.com/open-mpi/mtt/blob/a985719825e5377e9d558fdd968631602d0fd093/samples/python/ompi_snapshot_seq.ini#L59-L63), [3](https://github.com/open-mpi/mtt/blob/a985719825e5377e9d558fdd968631602d0fd093/samples/python/extensive_example.ini#L189-L193)), so they don't have TestBuild section for the Intel tests

**Comment by hppritcha** [comment]
HI Sai Sunku,

I’ll take a look at trying to run the intel tests.

Howard


From: Sai Sunku ***@***.***>
Reply-To: open-mpi/mtt ***@***.***>
Date: Monday, November 21, 2022 at 6:20 PM
To: open-mpi/mtt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [open-mpi/mtt] Intel test suite with Python client (Issue #938)


At AWS, we currently have a legacy system running the legacy Perl client. This system runs the IBM and Intel test suites. We are trying to move a new system that uses the Python client. We've figured out how to run the IBM suite but we don't know how to run the Intel suite.

The Test build section of the config in the legacy system looks like this

[Test build: ibm]

test_get = ibm

save_stdout_on_success = 1

merge_stdout_stderr = 1

stderr_save_lines = 100



module = Shell

shell_build_command = <<EOT

./configure --enable-static --disable-shared

make -j 32

EOT



#----------------------------------------------------------------------

[Test build: intel]

test_get = intel

save_stdout_on_success = 1

merge_stdout_stderr = 1

stderr_save_lines = 100

module = Intel_OMPI_Tests

intel_ompi_tests_buildfile = all_tests_no_perf

intel_ompi_tests_make_arguments = -j 32

The Intel suite is using module = Intel_OMPI_Tests. From what I can tell, modules in the legacy client are plugins in the Python client. What's the equivalent plugin to build the Intel tests?

When I search for Intel_OMPI_Tests, there are no results in the mtt repo and I just see configs using that module in ompi-tests<https://urldefense.com/v3/__https:/github.com/open-mpi/ompi-tests/search?p=1&q=Intel_OMPI_Tests__;!!Bt8fGhp8LhKGRg!BlS4BzQtMDSUIPRULTSY4BJYKqMkXYjhoEQpWlHtel23lFEFGvM2faOpCZKDlP1Ys-4x-0O54A4f13wxBrPSwFXy$>
I can’t find any code related to the Intel_OMPI_Tests module

The example configs for the new Python client that have the Intel tests all skip the Intel tests (1<https://urldefense.com/v3/__https:/github.com/open-mpi/mtt/blob/a985719825e5377e9d558fdd968631602d0fd093/samples/python/mpitest.ini*L66-L70__;Iw!!Bt8fGhp8LhKGRg!BlS4BzQtMDSUIPRULTSY4BJYKqMkXYjhoEQpWlHtel23lFEFGvM2faOpCZKDlP1Ys-4x-0O54A4f13wxBkvbyqEL$>, 2<https://urldefense.com/v3/__https:/github.com/open-mpi/mtt/blob/a985719825e5377e9d558fdd968631602d0fd093/samples/python/ompi_snapshot_seq.ini*L59-L63__;Iw!!Bt8fGhp8LhKGRg!BlS4BzQtMDSUIPRULTSY4BJYKqMkXYjhoEQpWlHtel23lFEFGvM2faOpCZKDlP1Ys-4x-0O54A4f13wxBn-i6AeX$>, 3<https://urldefense.com/v3/__https:/github.com/open-mpi/mtt/blob/a985719825e5377e9d558fdd968631602d0fd093/samples/python/extensive_example.ini*L189-L193__;Iw!!Bt8fGhp8LhKGRg!BlS4BzQtMDSUIPRULTSY4BJYKqMkXYjhoEQpWlHtel23lFEFGvM2faOpCZKDlP1Ys-4x-0O54A4f13wxBiR4GGxN$>), so they don't have TestBuild section for the Intel tests

**Comment by hppritcha** [comment]
HI Sai Sunku,

I got something to run but lots of the tests – well maybe all, are failing.
I will probably not have time to look in to this further till after thanksgiving holidays.

Howard


From: "Pritchard Jr., Howard" ***@***.***>
Date: Tuesday, November 22, 2022 at 11:36 AM
To: open-mpi/mtt ***@***.***>, open-mpi/mtt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [EXTERNAL] [open-mpi/mtt] Intel test suite with Python client (Issue #938)

HI Sai Sunku,

I’ll take a look at trying to run the intel tests.

Howard


From: Sai Sunku ***@***.***>
Reply-To: open-mpi/mtt ***@***.***>
Date: Monday, November 21, 2022 at 6:20 PM
To: open-mpi/mtt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [open-mpi/mtt] Intel test suite with Python client (Issue #938)


At AWS, we currently have a legacy system running the legacy Perl client. This system runs the IBM and Intel test suites. We are trying to move a new system that uses the Python client. We've figured out how to run the IBM suite but we don't know how to run the Intel suite.

The Test build section of the config in the legacy system looks like this

[Test build: ibm]

test_get = ibm

save_stdout_on_success = 1

merge_stdout_stderr = 1

stderr_save_lines = 100



module = Shell

shell_build_command = <<EOT

./configure --enable-static --disable-shared

make -j 32

EOT



#----------------------------------------------------------------------

[Test build: intel]

test_get = intel

save_stdout_on_success = 1

merge_stdout_stderr = 1

stderr_save_lines = 100

module = Intel_OMPI_Tests

intel_ompi_tests_buildfile = all_tests_no_perf

intel_ompi_tests_make_arguments = -j 32

The Intel suite is using module = Intel_OMPI_Tests. From what I can tell, modules in the legacy client are plugins in the Python client. What's the equivalent plugin to build the Intel tests?

When I search for Intel_OMPI_Tests, there are no results in the mtt repo and I just see configs using that module in ompi-tests<https://urldefense.com/v3/__https:/github.com/open-mpi/ompi-tests/search?p=1&q=Intel_OMPI_Tests__;!!Bt8fGhp8LhKGRg!BlS4BzQtMDSUIPRULTSY4BJYKqMkXYjhoEQpWlHtel23lFEFGvM2faOpCZKDlP1Ys-4x-0O54A4f13wxBrPSwFXy$>
I can’t find any code related to the Intel_OMPI_Tests module

The example configs for the new Python client that have the Intel tests all skip the Intel tests (1<https://urldefense.com/v3/__https:/github.com/open-mpi/mtt/blob/a985719825e5377e9d558fdd968631602d0fd093/samples/python/mpitest.ini*L66-L70__;Iw!!Bt8fGhp8LhKGRg!BlS4BzQtMDSUIPRULTSY4BJYKqMkXYjhoEQpWlHtel23lFEFGvM2faOpCZKDlP1Ys-4x-0O54A4f13wxBkvbyqEL$>, 2<https://urldefense.com/v3/__https:/github.com/open-mpi/mtt/blob/a985719825e5377e9d558fdd968631602d0fd093/samples/python/ompi_snapshot_seq.ini*L59-L63__;Iw!!Bt8fGhp8LhKGRg!BlS4BzQtMDSUIPRULTSY4BJYKqMkXYjhoEQpWlHtel23lFEFGvM2faOpCZKDlP1Ys-4x-0O54A4f13wxBn-i6AeX$>, 3<https://urldefense.com/v3/__https:/github.com/open-mpi/mtt/blob/a985719825e5377e9d558fdd968631602d0fd093/samples/python/extensive_example.ini*L189-L193__;Iw!!Bt8fGhp8LhKGRg!BlS4BzQtMDSUIPRULTSY4BJYKqMkXYjhoEQpWlHtel23lFEFGvM2faOpCZKDlP1Ys-4x-0O54A4f13wxBiR4GGxN$>), so they don't have TestBuild section for the Intel tests

**Comment by sunkuamzn** [comment]
Thank you for trying! We will continue using the Perl client in the meantime.

**Comment by sunkuamzn** [comment]
https://github.com/open-mpi/mtt/blob/master/samples/python/ompi_snapshot_seq.ini is an example config for running Intel tests
