### ISSUE TITLE
several places - likely - in MTT python code where iterating over keys in a dic and altering

### ISSUE THREAD

**Issue by hppritcha** [open-mpi/mtt#942]
With older versions of Python this was tolerated but not with newer versions.  Depending on the content of the ini file one can get exceptions of this form:
  
   Exception was raised: <class 'RuntimeError'> dictionary keys changed during iteration

See https://cito.github.io/blog/never-iterate-a-changing-dict/.

Some of the suspect loops are in LauncherMTTTool.py

**Comment by hppritcha** [comment]
closed via #944

**Comment by wckzhang** [comment]
@hppritcha it seems like you didn't close the issue
